### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by glenfe** [soasis/out_ptr#13]
New libraries should use `boost::library::` namespaces. e.g. `boost::out_pointer::` (or `boost::out_ptr::`, but `boost::out_ptr::out_ptr` doesn't look very nice).

i.e. Only the older existing libraries use just namespace `boost::`. All newer libraries have been required to create a namespace within `boost::` and use that.

Your detail namespace then becomes `boost::library::detail::`.

**Comment by ThePhD** [comment]
Oh. Okay. Picking a name for this is going to be a bit difficult...

**Comment by ThePhD** [comment]
I don't suppose `boost::ptr::out_ptr` is a good idea?

**Comment by glenfe** [comment]
The `library` namespace should correspond to the name of the library being proposed, so `'ptr` isn't a good fit (since you're not proposing Boost.Ptr). :)

**Comment by glenfe** [comment]
Looks good.
