### ISSUE TITLE
Double free on unset clever_out_ptr

### ISSUE THREAD

**Issue by Flamefire** [soasis/out_ptr#19]
If I read the implementation correctly, the clever_out_ptr can double-free the smart pointer.

Setup: 
- Have a `unique_ptr` with a value (non-NULL)
- Pass this into a function via clever_out_ptr
- function fails and does not set the pointer
- clever_out_ptr checks the original pointer, sees it is != null and calls the deleter
- deleter of `unique_ptr` calls delete on the same ptr

Am I missing anything or can you confirm this bug?

**Comment by uecasm** [comment]
Fortunately, `clever_out_ptr` is disabled in the current code.  But yes, this is one of many reasons why it's not safe to use it.

`out_ptr` must, with no possible alternative, pass a nullptr as input to the called function.

**Comment by ThePhD** [comment]
As stated, it's off by default. And it's likely to remain that way: I'd need a third type to signal that a nullptr-setting API. For now, it does not double free (and there are tests to prove it out).

**Comment by Flamefire** [comment]
> For now, it does not double free (and there are tests to prove it out).

Can you point me to the test mentioned? I described a sequence above which to my understanding will lead to a double free so I'm curious what I may have missed.

**Comment by ThePhD** [comment]
What I mean is clever_out_ptr is disabled, so there is no double freeing that occurs with regular usage. One would need to explicitly reach into the `detail` namespace and use `clever_out_ptr` directly to invoke the double-free.

It is off by default, therefore there is no double-freeing occurring.
