### ISSUE TITLE
Moving not initilaized this

### ISSUE THREAD

**Issue by Flamefire** [soasis/out_ptr#20]
https://github.com/ThePhD/out_ptr/blob/b4e7cf3e20cf0e5936f2611e83131984e2eabeef/include/boost/out_ptr/detail/base_out_ptr_impl.hpp#L78 is the move constructor and calls `Base(std::move(*this))`.

AFAIK this is UB because `this` (including the `Base` part of `this`) is not initialized, so it does access uninitialized memory -> UB

**Comment by ThePhD** [comment]
This is fixed in the `feature/boost.review` branch, which will be merged when the review is over.
